# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'BeaconServiceDemoApp' do
pod 'Google/SignIn'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'GooglePlacePicker'
end

target 'BeaconServiceDemoAppTests' do
pod 'Google/SignIn'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'GooglePlacePicker'
end

